# This file sets control variables for the internal control mechanisms in the actuators and 
# settings used throughout the driver.
# 
# It is **NOT** recommended to edit these values by hand.
# Parmeter changes, especially to PID, can cause unexpected behavior that poses a risk to the 
# robot and its environment.
#
# Don't do it!
#

1:
    p: 1200
    i: 0
    d: 9000
    acceleration: 16
    velocity: 200
    gr: 4
    mode: 5
2:
    p: 3000
    i: 0
    d: 12000
    acceleration: 28
    velocity: 350
    gr: 7
    mode: 5
3:
    p: 3000
    i: 0
    d: 9000
    acceleration: 28
    velocity: 350
    gr: 7
    mode: 5
4:
    p: 1600
    i: 0
    d: 8000
    acceleration: 12
    velocity: 150
    gr: 3
    mode: 5
5:
    p: 1200
    i: 0
    d: 8000
    acceleration: 16
    velocity: 200
    gr: 4
    mode: 5
6:
    p: 900
    i: 0
    d: 8000
    acceleration: 4
    velocity: 50
    gr: 1
    mode: 5
7:
    p: 500
    i: 0
    d: 900
    acceleration: 4
    velocity: 50
    gr: 1
    mode: 0

