dynamixel_controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint_1:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 0.5, i: 0.01, d: 0.1}

  joint_2:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 0.5, i: 0.01, d: 0.1}

  joint_3:
    type: effort_controllers/JointPositionController
    joint: joint_3
    pid: {p: 1.0, i: 0.1, d: 1.0}

  joint_4:
    type: effort_controllers/JointPositionController
    joint: joint_4
    pid: {p: 1.0, i: 0.1, d: 1.0}

  joint_5:
    type: effort_controllers/JointPositionController
    joint: joint_5
    pid: {p: 1.0, i: 0.1, d: 1.0}

  joint_6:
    type: effort_controllers/JointPositionController
    joint: joint_6
    pid: {p: 1.0, i: 0.1, d: 1.0}

dynamixel_control_hw:
  loop_frequency: 50
  cycle_time_error_threshold: 0.2
  serial_interface: /dev/ttyUSB0
  baudrate: 1000000 # in bauds
  dynamixel_timeout: 0.05 # in seconds
  dynamixel_scanning: 0.05 # in seconds
  # correspondance between hardware IDs of the actuators and their names in ROS
  hardware_mapping:
    first: 1
  # offset to be added, in ticks, to the position of an actuator
  hardware_corrections:
    "26": 45
